schema_version: 1

context:
  version: 0.2.3

package:
  name: spmd-types
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/spmd-types/spmd_types-${{ version }}.tar.gz
  sha256: 0bbeb783a7e9678a125cded42e07ef17c73982e4b4de2294d435f9df8c17331c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - pytorch >=2.6.0

tests:
  - python:
      imports:
        - spmd_types
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A type system for distributed (SPMD) tensor computations in PyTorch
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/meta-pytorch/spmd_types

extra:
  recipe-maintainers:
    - sarthakpati
